# Generated by Django 3.0.5 on 2020-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Uploaded image'),
        ),
    ]
