# Generated by Django 3.0.5 on 2020-04-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0002_auto_20200415_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
