# Generated by Django 3.0.5 on 2020-04-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0005_books_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
