# Generated by Django 3.0.5 on 2020-04-20 14:00

import bookss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0006_remove_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bookss.models.upload_article),
        ),
    ]
