# Generated by Django 3.0.5 on 2020-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0007_auto_20200420_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
