# Generated by Django 3.0.5 on 2020-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0010_auto_20200501_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
    ]
